services:
  eureka-server:
    build: eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'rentxpress-network'

  users-service:
    build: users-service
    mem_limit: 512m
    ports:
      - "9003:9003"
    networks:
      - 'rentxpress-network'

  vehicles-service:
    build: vehicles-service
    mem_limit: 512m
    ports:
      - "9002:9002"
    networks:
      - 'rentxpress-network'

  reservations-service:
    build: reservations-service
    mem_limit: 512m
    ports:
      - "9001:9001"
    networks:
      - 'rentxpress-network'

  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "431:431"
    networks:
      - 'rentxpress-network'

networks:
  rentxpress-network:
